version: '3'
services:
  fastcgi_server:
    build:
      context: .
      dockerfile: Dockerfile
  nginx_proxy:
    image: nginx
    ports:
      - "80:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastcgi_server

